import { useState } from "react";
import { CheckCircle, Key } from "lucide-react";
import { ApiError } from "../../shared/api/client";
import { redeemCode, type AccessGrant } from "../../shared/activation-codes/api";
import { Btn, Input2, notify } from "../../shared/ui";

export function ConnectedActivationPage({nav,params}:any){
  const [code,setCode]=useState("");const [grant,setGrant]=useState<AccessGrant|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
  const lectureId=Number(params?.lectureId)||0;
  const localizedError=(message:string)=>{const normalized=message.toLowerCase();return normalized.includes("expired")?"انتهت صلاحية هذا الكود":normalized.includes("grade")?"هذا الكود غير مخصص لصفك الدراسي":normalized.includes("already has access")?"لديك صلاحية الوصول لهذا الدرس بالفعل":normalized.includes("not redeemable")?"هذا الكود مستخدم أو معطل":normalized.includes("invalid")?"كود التفعيل غير صحيح":"تعذر تفعيل الكود";};
  const redeem=async()=>{if(!lectureId)return;setLoading(true);setError("");try{const response=await redeemCode(code,lectureId);setGrant(response.access_grant);notify("تم فتح المحاضرة بنجاح","success");}catch(reason){setError(reason instanceof ApiError?(localizedError(reason.rawMessage)==="تعذر تفعيل الكود"&&reason.status===422?"هذا الكود مستخدم أو معطل أو غير صالح":localizedError(reason.rawMessage)):"تعذر تفعيل الكود");}finally{setLoading(false);}};
  return <div className="activation-workspace"><section className="activation-story"><span className="workspace-eyebrow">خطوة واحدة للمحاضرة</span><h1>كودك معاك؟<br/>افتح باب جديد للفهم.</h1><p>كود واحد يفتح المحاضرة المدفوعة اللي تختارها من منهجك. اختار المحاضرة أولًا، وبعدها استخدم الكود هنا.</p><div className="activation-steps"><div><span>١</span>اختار المحاضرة من المنهج</div><div><span>٢</span>اكتب الكود زي ما وصلك</div><div><span>٣</span>كمّل التفعيل وابدأ المشاهدة</div></div></section><section className="activation-ticket">{grant?<><CheckCircle/><h2>محاضرتك اتفتحت.</h2><p>{grant.lecture??grant.lesson}</p><Btn className="w-full" onClick={()=>nav("video",{lessonId:grant.lecture_id??lectureId})}>ابدأ مشاهدة المحاضرة</Btn></>:!lectureId?<><Key/><h2>نبدأ باختيار المحاضرة</h2><p>افتح المنهج واختار المحاضرة المدفوعة اللي حابب تفعّلها. مش هنستخدم الكود قبل اختيارك.</p><Btn className="w-full" onClick={()=>nav("subjects")}>افتح المنهج واختر المحاضرة</Btn></>:<><Key/><h2>تفعيل المحاضرة المختارة</h2><p>راجع الكود قبل التأكيد؛ كل كود يُستخدم مرة واحدة فقط.</p><form className="space-y-4" onSubmit={event=>{event.preventDefault();void redeem();}}><Input2 label="كود المحاضرة" value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="اكتب الكود هنا" dir="ltr" autoComplete="off"/>{error&&<p role="alert">{error}</p>}<Btn type="submit" className="w-full" disabled={!code.trim()||loading}>{loading?"جارٍ التحقق…":"استخدام الكود وفتح المحاضرة"}</Btn></form></>}</section></div>;
}
