import type { ReactNode } from 'react';
import { BookOpen, CheckCircle, Clock, Send, ShieldCheck } from 'lucide-react';
import { arabicNumber as n } from '../../shared/arabic';

export function AssessmentIntro({title,homework,duration,attempts,pass,busy,onBegin}:{title:string;homework:boolean;duration:number;attempts:number;pass:number;busy:boolean;onBegin:()=>void}) {
  return <section className="assessment-intro"><div className="assessment-cover"><BookOpen size={38}/><span>مساحة التركيز والتطبيق</span><h2>{homework?'اختبر فهمك،\nوثبّت اللي اتعلمته.':'خُد نفس،\nوابدأ بثقة.'}</h2><p>{title}</p><i aria-hidden="true">ض</i></div><div className="assessment-preflight"><span className="workspace-eyebrow">قبل ما تبدأ</span><h2>كل التفاصيل قدامك</h2><dl><div><Clock/><dt>مدة التقييم</dt><dd>{n(duration)} دقيقة</dd></div><div><BookOpen/><dt>المحاولات المسموحة</dt><dd>{n(attempts)}</dd></div><div><ShieldCheck/><dt>نسبة النجاح</dt><dd>{n(pass)}٪</dd></div></dl><p>اقرأ كل سؤال بهدوء، وراجع اختياراتك قبل التسليم. التصحيح وعرض الإجابات حسب إعدادات المدرس.</p><button onClick={onBegin} disabled={busy}>{busy?'جارٍ البدء…':homework?'ابدأ الواجب':'ابدأ الاختبار'}<Send size={17}/></button></div></section>;
}
export function AssessmentSheet({questions,answered,children}:{questions:Array<{id:number}>;answered:Record<number,number>;children:ReactNode}) {
  const complete=questions.filter(q=>answered[q.id]!==undefined).length;
  return <div className="assessment-layout"><aside className="question-navigator"><span className="workspace-eyebrow">خريطة الأسئلة</span><h2>خطوة بخطوة</h2><p>أجبت عن {n(complete)} من {n(questions.length)} سؤال</p><progress max={questions.length||1} value={complete} aria-label="الأسئلة المجاب عنها"/><nav aria-label="الانتقال إلى سؤال">{questions.map((q,i)=><button type="button" key={q.id} onClick={()=>{const target=document.getElementById(`question-${q.id}`);if(target){target.setAttribute("tabindex","-1");target.focus({preventScroll:true});target.scrollIntoView({block:"start"});}}} className={answered[q.id]!==undefined?'question-answered':''} aria-label={`السؤال ${n(i+1)}${answered[q.id]!==undefined?'، تمت الإجابة':''}`}>{n(i+1)}</button>)}</nav><div className="question-legend"><CheckCircle size={15}/> المربع الملوّن يعني إنك اخترت إجابة.</div></aside><div className="assessment-questions">{children}</div></div>;
}
export function ResultHero({percent,points,max,attempt,label,children}:{percent:number|string|null|undefined;points:number|string|null|undefined;max:number|string|null|undefined;attempt:number;label:string;children?:ReactNode}) {
  return <section className="result-hero"><div className="result-seal"><span>{percent==null?'—':n(Math.round(Number(percent)))}<small>{percent==null?'':'٪'}</small></span><strong>{label||'تم التسليم'}</strong></div><div><span className="workspace-eyebrow">كل محاولة بتعلّمك حاجة</span><h2>نتيجتك وصلت.</h2><p>الدرجة {n(points??0)} من {n(max??0)} · المحاولة {n(attempt)}</p><p>راجع التفاصيل المتاحة، واعرف إيه الخطوة اللي محتاج تركز عليها.</p>{children}</div></section>;
}
