import { useState } from 'react';
import { ArrowLeft, CheckCircle, Clock, MessageCircle } from 'lucide-react';
import type { ExamAttempt, SupportRequest } from '../../shared/learning/api';
import { arabicNumber as n } from '../../shared/arabic';
const requestLabels={device_removal:'إزالة جهاز',extra_exam_attempt:'محاولة اختبار إضافية',parent_phone_change:'تغيير رقم ولي الأمر'};
const states={pending:'قيد المراجعة',approved:'مقبول',rejected:'مرفوض',cancelled:'ملغي'};
export function SupportInbox({items,onReview}:{items:SupportRequest[];onReview:(id:number,decision:'approve'|'reject')=>void}){
 const [filter,setFilter]=useState<'all'|'pending'|'done'>('all');const visible=items.filter(r=>filter==='all'||(filter==='pending'?r.status==='pending':r.status!=='pending'));
 return <div className="support-inbox"><aside className="support-filter"><MessageCircle size={30}/><h2>صندوق المتابعة</h2><p>فلترة الطلبات المعروضة في الصفحة الحالية.</p><nav aria-label="تصفية الطلبات">{([{id:'all',label:'كل الطلبات'},{id:'pending',label:'تحتاج مراجعة'},{id:'done',label:'تم التعامل معها'}] as const).map(f=><button type="button" key={f.id} aria-pressed={filter===f.id} onClick={()=>setFilter(f.id)}>{f.label}<span>{n(items.filter(r=>f.id==='all'||(f.id==='pending'?r.status==='pending':r.status!=='pending')).length)}</span></button>)}</nav></aside><div className="support-tickets">{!visible.length&&<div className="followup-empty"><CheckCircle/><h3>لا توجد طلبات هنا</h3><p>جرّب تصفية أخرى أو الانتقال لصفحة أخرى.</p></div>}{visible.map(r=><article key={r.id} className="support-ticket"><header><span className="ticket-number">{n(r.id)}</span><div><h3>{r.requester.name}</h3><p>{requestLabels[r.request_type]}</p></div><span className="ticket-state" data-status={r.status}>{states[r.status]}</span></header><p className="ticket-reason">{r.reason||'لم يُضف سبب للطلب.'}</p><footer><span><Clock size={14}/>{new Date(r.created_at).toLocaleDateString('ar-EG')}</span>{r.status==='pending'?<div><button type="button" onClick={()=>onReview(r.id,'approve')}>قبول الطلب</button><button type="button" onClick={()=>onReview(r.id,'reject')}>رفض الطلب</button></div>:<span>{r.actions.at(-1)?`راجعه ${r.actions.at(-1)?.reviewer_name}`:'تم تحديث حالة الطلب'}</span>}</footer>{r.actions.at(-1)&&<p className="ticket-history">آخر مراجعة: {new Date(r.actions.at(-1)!.created_at).toLocaleString('ar-EG')}</p>}</article>)}</div></div>;
}
export function ResultsJournal({attempts,onOpen}:{attempts:ExamAttempt[];onOpen:(id:number)=>void}){
 return <div className="results-journal">{!attempts.length&&<div className="followup-empty"><CheckCircle/><h3>النتائج هتظهر هنا بعد التسليم</h3><p>لا توجد محاولات مسلّمة في الصفحة الحالية.</p></div>}{attempts.map(a=><article key={a.id} className="result-entry"><div className="result-entry-score" data-passed={a.result_status==='passed'}><strong>{a.percent==null?'—':n(a.percent)}</strong><span>{a.percent==null?'غير متاحة':'٪'}</span></div><div className="result-entry-copy"><span>{a.student_name||'سجل المحاولة'}</span><h2>{a.exam_title}</h2><p>المحاولة {n(a.attempt_number)}{a.submitted_at?` · ${new Date(a.submitted_at).toLocaleDateString('ar-EG')}`:''}</p></div><button type="button" onClick={()=>onOpen(a.id)}>مراجعة التفاصيل <ArrowLeft size={16}/></button></article>)}</div>;
}
