import type { ReactNode } from 'react';
import { ArrowUpLeft, BookOpen, Check, ChevronLeft, ClipboardList, Clock, GraduationCap, KeyRound, Play, Sparkles, Users, Video } from 'lucide-react';
import type { Navigate } from '../../app/routing/types';
import type { ManagementDashboardData, StudentDashboardData } from '../../shared/dashboard/api';
import { arabicLabel, arabicNumber as n } from '../../shared/arabic';
import { useLectureThumbnailUrl } from '../../shared/media/lecture-thumbnail';

function Ring({value, label}:{value:number;label:string}) {
  const safe=Math.max(0,Math.min(100,value));
  return <div className="journey-ring" role="img" aria-label={`${label}: ${n(safe)}٪`}><svg viewBox="0 0 120 120" aria-hidden="true"><circle cx="60" cy="60" r="50"/><circle cx="60" cy="60" r="50" strokeDasharray={`${safe*3.1416} 314.16`}/></svg><div><strong>{n(safe)}<small>٪</small></strong><span>{label}</span></div></div>;
}
export function WorkspaceHeading({eyebrow,title,description,children}:{eyebrow:string;title:string;description:string;children?:ReactNode}) {
  return <div className="workspace-heading"><div><span className="workspace-eyebrow"><i/>{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{children}</div>;
}
function ResumeLesson({item,nav}:{item:NonNullable<StudentDashboardData['continue_watching']>;nav:Navigate}) {
  const image=useLectureThumbnailUrl(item.lecture_id,item.has_thumbnail);
  return <button className="resume-lesson" onClick={()=>nav('video',{lessonId:item.lecture_id})}><div className="resume-image">{image?<img src={image} alt={arabicLabel(item.title)}/>:<BookOpen size={64}/>}<span><Play fill="currentColor" size={22}/></span></div><div className="resume-copy"><span className="workspace-eyebrow">كمّل من حيث توقفت</span><h2>{arabicLabel(item.title)}</h2><p>{arabicLabel(item.subject_title)} · {arabicLabel(item.chapter_title)} · {arabicLabel(item.lesson_title)}</p><div className="resume-progress"><span style={{width:`${item.progress_percent}%`}}/></div><div className="resume-meta"><span>شاهدت {n(item.progress_percent)}٪ · عند الدقيقة {n(Math.floor(item.last_position_seconds/60))}:{n(String(item.last_position_seconds%60).padStart(2,'0'))}</span><strong>استكمل المحاضرة <ArrowUpLeft size={16}/></strong></div></div></button>;
}
export function StudentWorkspace({data,nav,name}:{data:StudentDashboardData;nav:Navigate;name?:string}) {
  const s=data.statistics;
  const progress=s.total_lectures?Math.round(s.completed_lectures/s.total_lectures*100):0;
  return <div className="workspace student-workspace"><WorkspaceHeading eyebrow="مساحتك للتعلّم" title={`أهلًا، ${name?.split(' ')[0]||'طالبنا'}.`} description={data.enrollment?`${arabicLabel(data.enrollment.grade)} · ${n(data.enrollment.academic_year)}`:'ابدأ رحلتك مع اللغة العربية'}><span className="workspace-date">{new Date().toLocaleDateString('ar-EG',{weekday:'long',day:'numeric',month:'long'})}</span></WorkspaceHeading>
    <div className="student-overview"><section className="learning-summary"><div><span className="workspace-eyebrow">خطوة صغيرة، أثر كبير</span><h2>{progress===100?'أتممت محاضراتك. أحسنت!':'رحلتك مستمرة،\nوكل درس بيفرق.'}</h2><p>أنجزت <strong>{n(s.completed_lectures)}</strong> من {n(s.total_lectures)} محاضرة متاحة في منهجك.</p><button onClick={()=>nav('subjects')}>افتح منهجك <ArrowUpLeft size={19}/></button></div><Ring value={progress} label="منهج مكتمل"/></section><div className="student-milestones"><div><GraduationCap/><span>أفضل نتيجة<strong>{s.highest_score===null?'لم تختبر بعد':`${n(Math.round(s.highest_score))}٪`}</strong></span></div><div><BookOpen/><span>فروع دراسية<strong>{n(s.subjects_count)} فروع</strong></span></div><div><KeyRound/><span>المحتوى المفعّل<strong>{n(s.active_access_grants)} صلاحية مشاهدة</strong></span><button aria-label="تفعيل محاضرة" onClick={()=>nav('activation')}><ChevronLeft/></button></div></div></div>
    <div className="workspace-columns"><div className="workspace-major">{data.continue_watching?<ResumeLesson item={data.continue_watching} nav={nav}/>:<section className="workspace-empty"><BookOpen/><h2>أول محاضرة في انتظارك</h2><p>اختار فرعًا من منهجك وابدأ المشاهدة.</p><button onClick={()=>nav('subjects')}>اكتشف المحاضرات <ArrowUpLeft size={17}/></button></section>}
      <div className="section-heading"><h2>منهجك، خطوة بخطوة</h2><button onClick={()=>nav('subjects')}>كل الفروع <ChevronLeft size={15}/></button></div><div className="subject-paths">{data.subjects.map((subject,i)=>{const p=subject.total_lectures?Math.round(subject.completed_lectures/subject.total_lectures*100):0;return <button key={subject.id} onClick={()=>nav('subjects')}><span className="path-order">{n(i+1)}</span><div><h3>{arabicLabel(subject.title)}</h3><p>{n(subject.completed_lectures)} من {n(subject.total_lectures)} محاضرة</p><div className="path-track"><i style={{width:`${p}%`}}/></div></div><span className="path-percent">{n(p)}٪</span><ChevronLeft size={18}/></button>;})}{!data.subjects.length&&<p className="workspace-muted">لم يُنشر منهج لصفك بعد.</p>}</div></div>
      <aside className="workspace-rail"><section className="practice-card"><ClipboardList/><span className="workspace-eyebrow">الفهم يكتمل بالتطبيق</span><h2>وقت التدريب.</h2><p>راجع واجباتك، وجرب اللي اتعلمته.</p><button onClick={()=>nav('homeworks')}>افتح واجباتي <ArrowUpLeft size={19}/></button><small>المحاولات المتبقية: {n(s.attempts_remaining)}</small></section><section className="notice-board"><div className="section-heading"><h2>على لوحة الإعلانات</h2><button onClick={()=>nav('announcements')} aria-label="كل الإعلانات"><ArrowUpLeft size={17}/></button></div>{data.announcements.map(a=><article key={a.id}><i/><div><h3>{arabicLabel(a.title)}</h3><p>{arabicLabel(a.body)}</p></div></article>)}{!data.announcements.length&&<p>لا توجد إعلانات جديدة. تابع هنا كل جديد.</p>}</section></aside></div></div>;
}
export function ManagementWorkspace({data,nav,role}:{data:ManagementDashboardData;nav:Navigate;role:'teacher'|'assistant'}) {
  const s=data.statistics; const active=s.total_students?Math.round(s.active_students/s.total_students*100):0;
  const max=Math.max(1,...data.most_watched.map(x=>x.views));
  return <div className="workspace management-workspace"><WorkspaceHeading eyebrow={role==='teacher'?'مساحة الأستاذ':'مساحة المساعد'} title="الصورة كاملة، في مكان واحد." description="تابع التعلّم، راجع ما يحتاج انتباهك، وحدد خطوتك التالية."><span className="live-badge"><i/>بيانات المنصة الحالية</span></WorkspaceHeading>
    <div className="management-overview"><section className="audience-panel"><div><span className="workspace-eyebrow">مجتمع المنصة</span><strong className="audience-total">{n(s.total_students)}</strong><p>طالب مسجل في المنصة</p><div className="audience-legend"><span><i/>{n(s.active_students)} نشط</span><span>{n(s.inactive_students)} غير نشط منذ ٣٠ يومًا</span></div></div><Ring value={active} label="طلاب نشطون"/></section><section className="attention-panel"><span className="workspace-eyebrow">يستحق انتباهك</span><h2>الأولوية اليوم</h2><div><Users/><span>طلاب يحتاجون متابعة</span><strong>{n(s.risk_students)}</strong></div><div><Clock/><span>طلبات دعم معلّقة</span><strong>{n(s.pending_support_requests)}</strong></div><div><Video/><span>فيديوهات تعذرت معالجتها</span><strong>{n(s.failed_videos)}</strong></div><p>مؤشرات من بيانات المنصة، وليست مهامًا منشأة تلقائيًا.</p></section></div>
    <div className="workspace-columns"><div className="workspace-major"><section className="workspace-panel"><div className="section-heading"><div><span className="workspace-eyebrow">ما يتابعه طلابك</span><h2>المحاضرات الأكثر مشاهدة</h2></div><Video/></div><div className="watch-chart">{data.most_watched.map((item,i)=><div key={item.id}><span>{n(i+1)}</span><div><strong>{arabicLabel(item.title)}</strong><div><i style={{width:`${item.views/max*100}%`}}/></div></div><b>{n(item.views)}<small>مشاهدة</small></b></div>)}{!data.most_watched.length&&<p className="workspace-muted">تظهر المقارنة هنا بعد أول مشاهدات للطلاب.</p>}</div></section>
    <section className="workspace-panel"><div className="section-heading"><div><span className="workspace-eyebrow">حركة المحتوى</span><h2>آخر التعديلات</h2></div><span className="count-label">{n(data.recent_content.length)} عناصر</span></div><div className="content-timeline">{data.recent_content.map(item=><article key={item.id}><span className="timeline-dot"/><div><h3>{arabicLabel(item.title)}</h3><p>{new Date(item.updated_at).toLocaleString('ar-EG')}</p></div><span className={`content-state state-${item.status==='published'?'published':'other'}`}>{arabicLabel(item.status)}</span></article>)}{!data.recent_content.length&&<p className="workspace-muted">لم يُضف محتوى بعد.</p>}</div></section></div>
    <aside className="workspace-rail"><section className="workspace-panel leaderboard"><div className="section-heading"><h2>طلاب متميزون</h2><Sparkles/></div>{data.top_students.map((student,i)=><button key={student.id} onClick={()=>nav('student-detail',{studentId:student.id})}><span className="rank">{n(i+1)}</span><span className="student-initial">{student.name.charAt(0)}</span><strong>{student.name}<small>أعلى نتيجة محققة</small></strong><b>{n(Math.round(student.highest_score))}٪</b></button>)}{!data.top_students.length&&<p className="workspace-muted">النتائج الأولى هتظهر هنا.</p>}</section><section className="processing-panel"><span className="workspace-eyebrow">خلف الكواليس</span><h2>جاهزية المحتوى</h2><div className="processing-total"><Check/><strong>{n(s.ready_videos)}</strong><span>فيديو جاهز</span></div><dl><div><dt>قيد المعالجة</dt><dd>{n(s.processing_videos)}</dd></div><div><dt>محتوى مسودة</dt><dd>{n(s.draft_content)}</dd></div><div><dt>مهام في الانتظار</dt><dd>{n(s.queued_jobs)}</dd></div><div><dt>مهام متعثرة</dt><dd>{n(s.failed_jobs)}</dd></div><div><dt>معالجات نشطة</dt><dd>{n(s.queue_workers)}</dd></div></dl></section></aside></div></div>;
}
