import type { AppRoute, Role } from "./types";

export const ROUTE_POLICY: Record<AppRoute, readonly Role[]> = {
  "not-found": ["guest", "student", "parent", "teacher", "assistant"],
  home: ["guest", "student", "parent", "teacher", "assistant"],
  login: ["guest", "student", "parent", "teacher", "assistant"],
  register: ["guest"],
  "parent-register": ["guest"],
  otp: ["guest"],
  forgot: ["guest"],
  "free-content": ["guest", "student", "parent", "teacher", "assistant"],
  about: ["guest", "student", "parent", "teacher", "assistant"],
  "arabic-secondary": ["guest", "student", "parent", "teacher", "assistant"],
  "arabic-first-secondary": ["guest", "student", "parent", "teacher", "assistant"],
  "arabic-second-secondary": ["guest", "student", "parent", "teacher", "assistant"],
  "arabic-third-secondary": ["guest", "student", "parent", "teacher", "assistant"],
  "nahw-secondary": ["guest", "student", "parent", "teacher", "assistant"],
  "balagha-secondary": ["guest", "student", "parent", "teacher", "assistant"],
  "student-dashboard": ["student"],
  subjects: ["student"],
  chapters: ["student"],
  lessons: ["student"],
  video: ["student", "teacher", "assistant"],
  exam: ["student"],
  homeworks: ["student"],
  "exam-result": ["student"],
  "error-review": ["student", "parent"],
  progress: ["student"],
  announcements: ["student", "parent", "teacher", "assistant"],
  activation: ["student"],
  "student-settings": ["student"],
  "parent-dashboard": ["parent"],
  "parent-results": ["parent"],
  "parent-errors": ["parent"],
  "admin-dashboard": ["teacher", "assistant"],
  "assistant-dashboard": ["assistant"],
  "students-list": ["teacher", "assistant"],
  "student-detail": ["teacher", "assistant"],
  "parents-list": ["teacher"],
  "parent-detail": ["teacher"],
  "student-preview": ["teacher"],
  "management-reports": ["teacher", "assistant"],
  "content-subjects": ["teacher", "assistant"],
  "exam-manage": ["teacher", "assistant"],
  "homework-manage": ["teacher", "assistant"],
  "activation-codes": ["teacher", "assistant"],
  "announcements-admin": ["teacher", "assistant"],
  assistants: ["teacher"],
  "audit-log": ["teacher", "assistant"],
  "support-requests": ["teacher", "assistant"],
  "academic-years": ["teacher", "assistant"],
};

export const ROLE_DEFAULT: Record<Role, AppRoute> = {
  guest: "home",
  student: "student-dashboard",
  parent: "parent-dashboard",
  teacher: "admin-dashboard",
  assistant: "admin-dashboard",
};

export function canAccess(role: Role, route: AppRoute): boolean {
  return ROUTE_POLICY[route].includes(role);
}
