import { useEffect, useState } from "react";
import { ArrowRight, BarChart3, Eye, Search, ShieldCheck, Users } from "lucide-react";
import { ApiError } from "../../shared/api/client";
import { loadAcademicYears, loadGrades, type AcademicYear, type Grade } from "../../shared/admin/day5";
import { loadManagementReport, loadParent, loadParents, loadStudentPreview, resetParentPassword, updateParent, type ManagementReport, type ParentRecord, type StudentPreview } from "../../shared/admin/teacher-control";
import { Badge2, Btn, Card2, Field, Input2, Modal2, Select2, StatCard, notify } from "../../shared/ui";
import { emptyPagination, PaginationControls, type PaginationMeta } from "../../shared/pagination";

const errorMessage=(error:unknown,fallback:string)=>error instanceof ApiError?error.message:fallback;
const date=(value?:string|null)=>value?new Date(value).toLocaleString("ar-EG"):"—";
const gradeName=(level?:number,name?:string)=>level===1?"الصف الأول الثانوي":level===2?"الصف الثاني الثانوي":level===3?"الصف الثالث الثانوي":name||"—";
const accountStatus:Record<ParentRecord["status"],string>={active:"نشط",suspended:"موقوف",archived:"مؤرشف"};
const relationName:Record<string,string>={father:"الأب",mother:"الأم",guardian:"ولي الأمر",other:"قريب"};

export function ParentsListPage({nav}:any){
  const [parents,setParents]=useState<ParentRecord[]>([]);const [query,setQuery]=useState("");const [status,setStatus]=useState("");const [loading,setLoading]=useState(true);const [page,setPage]=useState(1);const [pagination,setPagination]=useState<PaginationMeta>(emptyPagination);
  useEffect(()=>{setPage(1);},[query,status]);
  useEffect(()=>{const timer=setTimeout(()=>{setLoading(true);loadParents(query,status,page).then(r=>{setParents(r.parents);setPagination(r.pagination);}).catch(e=>notify(errorMessage(e,"تعذر تحميل أولياء الأمور"),"error")).finally(()=>setLoading(false));},250);return()=>clearTimeout(timer);},[query,status,page]);
  return <div className="min-h-screen bg-background p-4 sm:p-6"><div className="mx-auto max-w-6xl"><div className="mb-5 flex items-center justify-between"><h1 className="text-2xl font-black">حسابات أولياء الأمور</h1><Badge2 variant="primary">{pagination.total_count} حساب</Badge2></div><Card2 className="mb-4"><div className="grid gap-3 sm:grid-cols-2"><Field label="بحث"><div className="relative"><Search size={15} className="absolute right-3 top-3 text-muted-foreground"/><input aria-label="بحث" value={query} onChange={e=>setQuery(e.target.value)} placeholder="الاسم أو رقم الهاتف" className="w-full rounded-xl border border-border bg-background py-2.5 pr-9 pl-3"/></div></Field><Select2 label="الحالة" value={status} onChange={(e:any)=>setStatus(e.target.value)} options={[{value:"",label:"كل الحالات"},{value:"active",label:"نشط"},{value:"suspended",label:"موقوف"},{value:"archived",label:"مؤرشف"}]}/></div></Card2><div className="space-y-3">{parents.map(parent=><Card2 key={parent.id}><div className="flex items-center gap-3"><Users className="text-primary"/><div className="flex-1"><strong>{parent.name}</strong><p className="text-xs text-muted-foreground" dir="ltr">{parent.phone}</p><p className="mt-1 text-xs">{parent.students_count} طالب مرتبط • آخر نشاط: {date(parent.last_active_at)}</p></div><Badge2 variant={parent.status==="active"?"success":"danger"}>{parent.status==="active"?"نشط":"غير نشط"}</Badge2><Btn size="sm" variant="outline" onClick={()=>nav("parent-detail",{parentId:parent.id})}><Eye size={14}/> إدارة</Btn></div></Card2>)}{!loading&&!parents.length&&<Card2><p className="py-8 text-center text-muted-foreground">لا توجد حسابات مطابقة.</p></Card2>}</div><PaginationControls pagination={pagination} onPageChange={setPage}/></div></div>;
}

export function ParentDetailPage({nav,params}:any){
  const [parent,setParent]=useState<ParentRecord|null>(null);const [passwordModal,setPasswordModal]=useState(false);const [password,setPassword]=useState("");
  const refresh=()=>loadParent(Number(params?.parentId)).then(r=>setParent(r.parent)).catch(e=>notify(errorMessage(e,"تعذر تحميل حساب ولي الأمر"),"error"));useEffect(()=>{void refresh();},[params?.parentId]);
  if(!parent)return <p className="p-8 text-center">جارٍ تحميل الحساب…</p>;
  const toggle=async()=>{const status=parent.status==="active"?"suspended":"active";const r=await updateParent(parent.id,{status});setParent(r.parent);notify(status==="active"?"تم تفعيل الحساب":"تم إيقاف الحساب وإنهاء جلساته","success");};
  const savePassword=async()=>{await resetParentPassword(parent.id,password);setPassword("");setPasswordModal(false);notify("تم تغيير كلمة المرور وإنهاء الجلسات القديمة","success");};
  return <div className="min-h-screen bg-background p-4 sm:p-6"><div className="mx-auto max-w-4xl"><button onClick={()=>nav("parents-list")} className="mb-4 flex items-center gap-1 text-sm text-muted-foreground"><ArrowRight size={14}/> العودة لأولياء الأمور</button><Card2><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-black">{parent.name}</h1><p dir="ltr" className="text-sm text-muted-foreground">{parent.phone}</p></div><div className="flex gap-2"><Btn variant="outline" onClick={()=>setPasswordModal(true)}>تغيير كلمة المرور</Btn><Btn variant={parent.status==="active"?"danger":"primary"} onClick={toggle}>{parent.status==="active"?"إيقاف الحساب":"تفعيل الحساب"}</Btn></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-muted p-3"><span className="text-xs text-muted-foreground">الحالة</span><p className="font-bold">{accountStatus[parent.status]}</p></div><div className="rounded-xl bg-muted p-3"><span className="text-xs text-muted-foreground">آخر نشاط</span><p className="font-bold">{date(parent.last_active_at)}</p></div></div></Card2><Card2 className="mt-4"><h2 className="mb-3 font-black">الطلاب المرتبطون</h2>{parent.students?.map(student=><div key={student.id} className="flex items-center justify-between border-t border-border py-3"><div><strong>{student.name}</strong><p dir="ltr" className="text-xs text-muted-foreground">{student.phone}</p></div><div className="flex gap-2"><Badge2>{relationName[student.relation]||"ولي الأمر"}</Badge2><Btn size="sm" variant="outline" onClick={()=>nav("student-detail",{studentId:student.id})}>إدارة الطالب</Btn><Btn size="sm" onClick={()=>nav("student-preview",{studentId:student.id})}>معاينة كطالب</Btn></div></div>)}</Card2><Modal2 open={passwordModal} onClose={()=>setPasswordModal(false)} title="تغيير كلمة مرور ولي الأمر"><div className="space-y-3"><Input2 label="كلمة المرور الجديدة" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><Btn className="w-full" disabled={password.length<8} onClick={savePassword}>حفظ وإنهاء الجلسات</Btn></div></Modal2></div></div>;
}

export function StudentPreviewPage({nav,params}:any){
  const [preview,setPreview]=useState<StudentPreview|null>(null);useEffect(()=>{loadStudentPreview(Number(params?.studentId)).then(r=>setPreview(r.preview)).catch(e=>notify(errorMessage(e,"تعذر تحميل المعاينة"),"error"));},[params?.studentId]);if(!preview)return <p className="p-8 text-center">جارٍ تجهيز المعاينة…</p>;
  return <div className="min-h-screen bg-background p-4 sm:p-6"><div className="mx-auto max-w-5xl"><div className="mb-4 rounded-2xl border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900"><ShieldCheck size={16} className="ml-1 inline"/>هذه معاينة للبيانات التي يراها الطالب، دون الدخول إلى حسابه أو تغيير تقدمه.</div><div className="mb-5 flex items-center justify-between"><div><h1 className="text-2xl font-black">معاينة لوحة {preview.student.name}</h1><p className="text-sm text-muted-foreground">{preview.enrollment?`${gradeName(preview.enrollment.grade_level,preview.enrollment.grade)} • ${preview.enrollment.academic_year}`:"غير مسجل في سنة دراسية"}</p></div><Btn variant="outline" onClick={()=>nav("student-detail",{studentId:preview.student.id})}>العودة لإدارة الطالب</Btn></div><div className="grid gap-3 sm:grid-cols-4"><StatCard label="المواد" value={preview.statistics.subjects_count} icon={Users}/><StatCard label="المحاضرات" value={preview.statistics.total_lectures} icon={Eye}/><StatCard label="المكتمل" value={preview.statistics.completed_lectures} icon={ShieldCheck}/><StatCard label="أعلى نتيجة" value={preview.statistics.highest_score==null?"—":`${Math.round(preview.statistics.highest_score)}%`} icon={BarChart3}/></div><Card2 className="mt-4"><h2 className="mb-3 font-black">المواد الظاهرة للطالب</h2>{preview.subjects.map(subject=><div key={subject.id} className="flex justify-between border-t border-border py-3"><strong>{subject.title}</strong><span className="text-sm text-muted-foreground">{subject.completed_lectures} من {subject.total_lectures} مكتمل</span></div>)}{!preview.subjects.length&&<p className="text-sm text-muted-foreground">لا يوجد محتوى منشور ظاهر لهذا الطالب.</p>}</Card2></div></div>;
}

export function ManagementReportsPage({nav}:any){
  const [report,setReport]=useState<ManagementReport|null>(null);const [years,setYears]=useState<AcademicYear[]>([]);const [grades,setGrades]=useState<Grade[]>([]);const [yearId,setYearId]=useState(0);const [gradeId,setGradeId]=useState(0);const [page,setPage]=useState(1);const [pagination,setPagination]=useState<PaginationMeta>(emptyPagination);
  useEffect(()=>{Promise.all([loadAcademicYears(),loadGrades()]).then(([y,g])=>{setYears(y.academic_years);setGrades(g.grades);});},[]);useEffect(()=>{setPage(1);},[yearId,gradeId]);useEffect(()=>{loadManagementReport(yearId||undefined,gradeId||undefined,page).then(r=>{setReport(r.report);setPagination(r.pagination);}).catch(e=>notify(errorMessage(e,"تعذر تحميل التقارير"),"error"));},[yearId,gradeId,page]);
  if(!report)return <p className="p-8 text-center">جارٍ تحميل التقارير…</p>;const o=report.overview;
  return <div className="min-h-screen bg-background p-4 sm:p-6"><div className="mx-auto max-w-7xl"><h1 className="mb-5 text-2xl font-black">التقارير التفصيلية</h1><Card2 className="mb-4"><div className="grid gap-3 sm:grid-cols-2"><Select2 label="السنة الدراسية" value={String(yearId)} onChange={(e:any)=>setYearId(Number(e.target.value))} options={[{value:"0",label:"كل السنوات"},...years.map(y=>({value:String(y.id),label:y.name}))]}/><Select2 label="الصف" value={String(gradeId)} onChange={(e:any)=>setGradeId(Number(e.target.value))} options={[{value:"0",label:"كل الصفوف"},...grades.map(g=>({value:String(g.id),label:gradeName(g.level,g.name)}))]}/></div></Card2><div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6"><StatCard label="الطلاب" value={o.students_count} icon={Users}/><StatCard label="المحاولات" value={o.attempts_count} icon={BarChart3}/><StatCard label="متوسط النتائج" value={o.average_score==null?"—":`${Math.round(o.average_score)}%`} icon={BarChart3}/><StatCard label="ناجح" value={o.passed_count} icon={ShieldCheck}/><StatCard label="في خطر" value={o.risk_count} icon={Eye}/><StatCard label="راسب" value={o.failed_count} icon={Eye}/></div><Card2 className="mt-4 !p-0 overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted"><tr><th className="p-3 text-right">الطالب</th><th className="p-3 text-right">الصف</th><th className="p-3 text-center">متوسط النتيجة</th><th className="p-3 text-center">المحاولات</th><th className="p-3 text-center">المحاضرات المكتملة</th><th className="p-3 text-center">آخر نشاط</th></tr></thead><tbody>{report.students.map(student=><tr key={student.id} className="border-t border-border cursor-pointer hover:bg-muted/50" onClick={()=>nav("student-detail",{studentId:student.id})}><td className="p-3 font-bold">{student.name}</td><td className="p-3">{gradeName(grades.find(g=>g.name===student.grade)?.level,student.grade)}</td><td className="p-3 text-center">{student.average_score==null?"—":`${Math.round(student.average_score)}%`}</td><td className="p-3 text-center">{student.attempts_count}</td><td className="p-3 text-center">{student.completed_lectures}</td><td className="p-3 text-center">{date(student.last_active_at)}</td></tr>)}</tbody></table></div></Card2><PaginationControls pagination={pagination} onPageChange={setPage}/></div></div>;
}
