import { ArrowUpLeft, CheckCircle, GraduationCap, ShieldCheck } from 'lucide-react';
import type { Navigate } from '../../app/routing/types';
import type { LinkedStudent } from '../../shared/auth/profile';
import type { ExamAttempt } from '../../shared/learning/api';
import { arabicLabel, arabicNumber as n } from '../../shared/arabic';
import { WorkspaceHeading } from '../dashboard/workspace-views';
export function ParentWorkspace({students,student,attempts,onSelect,nav}:{students:LinkedStudent[];student:LinkedStudent;attempts:ExamAttempt[];onSelect:(id:number)=>void;nav:Navigate}) {
  const highest=attempts.length?Math.max(...attempts.map(a=>Number(a.percent??0))):null;
  const passed=attempts.filter(a=>a.result_status==='passed').length;
  return <div className="workspace parent-workspace"><WorkspaceHeading eyebrow="مساحة ولي الأمر" title="قريب من رحلته، خطوة بخطوة." description="نتائج واضحة تساعدك تتابع وتدعم، من غير ما تفوّتك التفاصيل."/>
    <div className="family-tabs" aria-label="الطلاب المرتبطون">{students.map(s=><button key={s.id} aria-pressed={student.id===s.id} onClick={()=>onSelect(s.id)}><span>{s.name.charAt(0)}</span>{s.name}{student.id===s.id&&<CheckCircle size={16}/>}</button>)}</div>
    <div className="workspace-columns"><aside className="family-profile"><div className="family-avatar">{student.name.charAt(0)}</div><span className="workspace-eyebrow">ملف الطالب</span><h2>{student.name}</h2><p>{arabicLabel(student.grade||({1:'الصف الأول الثانوي',2:'الصف الثاني الثانوي',3:'الصف الثالث الثانوي'}[student.grade_level||0 as 1]||'الصف غير محدد'))}</p><span className="family-status">{student.status==='active'?'الحساب نشط':'الحساب غير نشط'}</span><dl><div><dt>السنتر</dt><dd>{student.center_name||'غير مسجل'}</dd></div><div><dt>المحافظة</dt><dd>{student.governorate||'غير مسجلة'}</dd></div><div><dt>المدرسة</dt><dd>{student.school||'غير مسجلة'}</dd></div><div><dt>آخر نشاط</dt><dd>{student.last_active_at?new Date(student.last_active_at).toLocaleDateString('ar-EG'):'لم يسجل نشاطًا'}</dd></div></dl><div className="family-note"><ShieldCheck/><p>مساحة متابعة فقط. حل الاختبارات ومشاهدة المحاضرات من حساب الطالب.</p></div></aside>
    <div className="workspace-major"><section className="family-summary"><GraduationCap/><div><span>أعلى نتيجة محققة</span><strong>{highest===null?'لم يختبر بعد':`${n(Math.round(highest))}٪`}</strong></div><div><span>محاولات مكتملة</span><strong>{n(attempts.length)}</strong></div><div><span>نتائج ناجحة</span><strong>{n(passed)}</strong></div></section><section className="workspace-panel"><div className="section-heading"><div><span className="workspace-eyebrow">سجل التعلّم</span><h2>النتائج والمحاولات</h2></div><span className="count-label">{n(attempts.length)} محاولة</span></div><div className="family-attempts">{attempts.map(a=><article key={a.id}><div className={`score-medallion ${a.result_status==='passed'?'passed':'review'}`}><strong>{n(Math.round(Number(a.percent??0)))}٪</strong><small>{a.result_status==='passed'?'ناجح':'يحتاج مراجعة'}</small></div><div><h3>{a.exam_title}</h3><p>{new Date(a.submitted_at??a.started_at).toLocaleDateString('ar-EG')} · المحاولة {n(a.attempt_number)}</p><span>الدرجة {n(a.score_points??0)} من {n(a.max_points??0)}</span></div><button onClick={()=>nav('parent-errors',{attemptId:a.id})}>مراجعة الإجابات <ArrowUpLeft size={17}/></button></article>)}{!attempts.length&&<div className="workspace-empty"><GraduationCap/><h3>النتائج في انتظار أول محاولة</h3><p>بعد ما الطالب يسلّم الاختبار، هتظهر نتيجته وتفاصيل إجاباته هنا.</p></div>}</div></section></div></div></div>;
}
