import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import process from 'node:process';
import { gzipSync } from 'node:zlib';
const root=path.resolve('dist');
assert.ok(fs.existsSync(root),'Build the frontend before release verification');
const files=[];
function walk(dir){for(const item of fs.readdirSync(dir,{withFileTypes:true})){const name=path.join(dir,item.name);if(item.isDirectory())walk(name);else files.push(name);}}
walk(root);
assert.ok(!files.some(f=>f.endsWith('.map')),'Public source maps found');
assert.ok(!files.some(f=>/atelier-review|design-review|\.env/i.test(f)),'Preview or environment file found in release');
for(const name of ['index.html','robots.txt','sitemap.xml','about/index.html','free-content/index.html'])assert.ok(fs.existsSync(path.join(root,name)),`Missing ${name}`);
const js=files.filter(f=>f.endsWith('.js')).map(f=>fs.readFileSync(f,'utf8')).join('\n');
assert.ok(js.includes('https://api.mourdy.com/api'),'Production API endpoint missing');
assert.ok(!js.includes('http://localhost:3000/api'),'Local API endpoint found in production');
assert.ok(!fs.readFileSync(path.join(root,'robots.txt'),'utf8').match(/Disallow:\s*\/\s*$/m),'Entire website disallowed');
const assetGzipSize=(name)=>gzipSync(fs.readFileSync(name)).byteLength;
const cssBundle=files.find(name=>/assets[\\/]index-[^\\/]+\.css$/.test(name));
const videoBundle=files.find(name=>/assets[\\/]connected-video-page-[^\\/]+\.js$/.test(name));
const hlsBundle=files.find(name=>/assets[\\/]hls-[^\\/]+\.js$/.test(name));
assert.ok(cssBundle && videoBundle && hlsBundle,'Main CSS, video page, or HLS bundle missing');
const cssKilobytes=assetGzipSize(cssBundle)/1024;
const videoKilobytes=assetGzipSize(videoBundle)/1024;
const hlsKilobytes=assetGzipSize(hlsBundle)/1024;
assert.ok(cssKilobytes <= 40, `Main CSS exceeds 40 KiB gzip: ${cssKilobytes.toFixed(1)}`);
assert.ok(videoKilobytes <= 40, `Video page exceeds 40 KiB gzip: ${videoKilobytes.toFixed(1)}`);
assert.ok(hlsKilobytes <= 220, `HLS player exceeds 220 KiB gzip: ${hlsKilobytes.toFixed(1)}`);
process.stdout.write(`Asset budgets: CSS ${cssKilobytes.toFixed(1)} KiB, video page ${videoKilobytes.toFixed(1)} KiB, HLS ${hlsKilobytes.toFixed(1)} KiB gzip.\n`);
process.stdout.write(`Release files verified: ${files.length}. No upload or deployment performed.\n`);
